---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm install -g npm@^2"
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember server &
  - sleep 5
  - npm test

notifications:
  flowdock: 7810528ead9733543fd77e874400b1c1
