version: 2

aliases:

  - defaults: &defaults
      docker:
        - image: circleci/node:boron
      working_directory: ~/code
  - &restore-repo-cache
      key: app-goodcity-repo-{{ .Environment.CIRCLE_SHA1 }}
  - &restore-yarn-cache
      keys:
        - app-goodcity-yarn-packages-{{ checksum "yarn.lock" }}
  - &save-yarn-cache
      key: app-goodcity-yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - node_modules
        - ~/.cache/yarn
  - &yarn
    |
      yarn install --non-interactive --cache-folder ~/.cache/yarn --frozen-lockfile
  - &restore-bower-cache
      key: app-goodcity-bower-components-{{ checksum "bower.json" }}
  - &save-bower-cache
      key: app-goodcity-bower-components-{{ checksum "bower.json" }}
      paths:
        - bower_components
  - &restore-bundler-cache
      key: app-goodcity-bundle-{{ checksum "Gemfile.lock" }}
  - &save-bundler-cache
      key: app-goodcity-bundle-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          key: app-goodcity-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/code

  package_dependencies:
    <<: *defaults
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache
      - restore-cache: *restore-bower-cache
      - run: yarn run bower install
      - save-cache: *save-bower-cache

  tests:
    <<: *defaults
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - restore-cache: *restore-bower-cache
      - run:
          name: Start Ember test server
          command: yarn run ember server --port 4200
          background: true
      - run:
          name: Wait for Ember test server to start
          command: dockerize -wait tcp://localhost:4200 -timeout 1m
      - run:
          name: Run Ember tests
          command: COVERAGE=true yarn run ember test
      - persist_to_workspace:
          root: .
          paths:
            - coverage*/lcov.info

  upload-coverage:
    <<: *defaults
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - restore-cache: *restore-bower-cache
      - attach_workspace:
          at: ~/code
      - run:
          name: Upload coverage results to Code Climate
          command: |
            yarn run codeclimate-test-reporter < coverage*/lcov.info

  ember_cordova_build:
    <<: *defaults
    environment:
        EMBER_CLI_CORDOVA: "1"
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - restore-cache: *restore-bower-cache
      - run:
          name: Setup Environment variables
          command: |
            echo 'export APP_SHA=$(echo $CIRCLE_SHA1 | cut -c1-7)' >> $BASH_ENV
            echo 'if [ -z "$APP_SHARED_SHA" ]; then export APP_SHARED_SHA=$( git ls-remote --heads https://github.com/crossroads/shared.goodcity.git $CIRCLE_BRANCH | cut -c1-7); fi' >> $BASH_ENV
            echo 'if [ -z "$APP_SHARED_SHA" ]; then export APP_SHARED_SHA=$( git ls-remote --heads https://github.com/crossroads/shared.goodcity.git master | cut -c1-7); fi' >> $BASH_ENV
            echo 'export STAGING=$(if [ "$CIRCLE_BRANCH" == "live" ]; then echo false; else echo true; fi)' >> $BASH_ENV
            echo 'export APP_VERSION=$(jq -r ".version" package.json)' >> $BASH_ENV
      - run:
          command: |
            npm rebuild node-sass
            echo "Building for staging (true/false): $STAGING"
            yarn run ember build --environment=production
      - run: mv dist/ cordova/www
      - persist_to_workspace:
          root: .
          paths:
            - cordova/www

  android_build_and_deploy:
    <<: *defaults
    docker:
      - image: circleci/android:api-26-node8-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      KEYSTORE: goodcity.keystore
      CIRCLE_ARTIFACTS: /home/circleci/code/cordova/platforms/android/build/outputs/apk

    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - restore-cache: *restore-bundler-cache
      - run: bundle install --deployment --jobs=4 --retry=3
      - save-cache: *save-bundler-cache
      - attach_workspace:
          at: ~/code
      - run:
          name: Setup Environment variables
          command: |
              echo 'export ENVIRONMENT=$(if [ "$CIRCLE_BRANCH" == "live" ]; then echo production; else echo staging; fi)' >> $BASH_ENV
              echo 'export PATH=$PATH:`yarn bin`' >> $BASH_ENV
              echo 'export PATH=$PATH:$ANDROID_HOME/tools/gradle/bin' >> $BASH_ENV
      - run:
          name: Install Gradle 4.10.2
          command: |
            wget -O /tmp/gradle.zip https://downloads.gradle.org/distributions/gradle-4.10.2-bin.zip
            unzip -d $ANDROID_HOME/tools /tmp/gradle.zip
            mv $ANDROID_HOME/tools/gradle-4.10.2 $ANDROID_HOME/tools/gradle
      - run:
          name: Download Keystore File
          command: yarn run azure-filestore download -f $KEYSTORE
          working_directory: cordova
      - run:
          name: Download Google Play Store Key file
          command: |
           yarn run azure-filestore download -d google-play -f $GOOGLE_PLAY_KEY_FILE
           mv $GOOGLE_PLAY_KEY_FILE ~/code/fastlane
          working_directory: ~/code
      - run:
          name: android build
          command: bundle exec rake ${ENVIRONMENT} android app:build
          working_directory: ~/code/cordova
      - store_artifacts:
          path: cordova/platforms/android/build/outputs/apk/
      - run:
          name: release android build
          command: bundle exec fastlane android ${ENVIRONMENT}
          working_directory: ~/code

  ios_build_and_deploy:
    macos:
      xcode: "9.2.0"
    working_directory: ~/code
    shell: /bin/bash --login -eo pipefail
    environment:
        EMBER_CLI_CORDOVA: "1"
        CIRCLE_ARTIFACTS: /Users/distiller/code/cordova/platforms/ios/build/device

    steps:
      - checkout
      - run: *yarn
      - save-cache: *save-yarn-cache
      - run: yarn run bower install
      - save-cache: *save-bower-cache
      - run:
          name: Setup Environment variables
          command: |
            echo 'export PATH=$PATH:`yarn bin`' >> $BASH_ENV
            echo 'export ENVIRONMENT=$(if [ "$CIRCLE_BRANCH" == "live" ]; then echo production; else echo staging; fi)' >> $BASH_ENV
            echo 'export PROVISIONING_PROFILE=$(if [ "$CIRCLE_BRANCH" == "live" ]; then echo $ENCODED_PROD_PROVISIONING_PROFILE; else echo $ENCODED_STAGING_PROVISIONING_PROFILE; fi)' >> $BASH_ENV
            echo 'export CERTIFICATES=$(if [ "$CIRCLE_BRANCH" == "live" ]; then echo $ENCODED_PROD_CERT; else echo $ENCODED_STAGING_CERT; fi)' >> $BASH_ENV
            echo 'export STAGING=$(if [ "$CIRCLE_BRANCH" == "live" ]; then echo false; else echo true; fi)' >> $BASH_ENV
      - run:
          command: |
              npm rebuild node-sass
              echo "Building for staging (true/false): $STAGING"
              yarn run ember build --environment=production
      - run: mv dist/ cordova/www
      - persist_to_workspace:
          root: .
          paths:
            - cordova/www
      - run: bundle check || bundle install --path vendor/bundle
      - save-cache: *save-bundler-cache
      - attach_workspace:
          at: ~/code
      - run:
          name: make Provisioning Profiles directory
          command: mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles/
      - run:
          name: decode Provisioning Profiles
          context: org-global
          command: base64 -D -o ~/Library/MobileDevice/Provisioning\ Profiles/App_Store.mobileprovision <<< "${PROVISIONING_PROFILE}"
      - run: pod setup
      - run:
          name: install cordova-update-config globally
          command: npm i -g cordova-update-config
      - run:
          name: install cordova globally
          command: npm i -g cordova@6.5.0
      - run:
          name: create keychain and import certificates
          command: bundle exec fastlane ios prepare_certificates cert:$CERTIFICATES
          working_directory: ~/code
      - run:
          name: iOS build
          command: bundle exec rake ${ENVIRONMENT} ios app:build
          working_directory: cordova
      - store_artifacts:
          path: cordova/platforms/ios/build/device
      - run:
          name: release ios build
          command: bundle exec fastlane ios ${ENVIRONMENT}
          working_directory: ~/code

  www_build:
    <<: *defaults
    environment:
      EMBER_CLI_CORDOVA: "0"
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - restore-cache: *restore-bower-cache
      - run:
          name: Setup Environment variables
          command: echo 'export STAGING=$(if [ "$CIRCLE_BRANCH" == "live" ]; then echo false; else echo true; fi)' >> $BASH_ENV
      - run:
          command: |
            npm rebuild node-sass
            echo "Building for staging (true/false): $STAGING"
            yarn run ember build --environment=production
      - run: mv dist/ dist-www
      - persist_to_workspace:
          root: .
          paths:
            - dist-www/

  www_deploy:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5.1-node
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-bundler-cache
      - run: bundle check --path=vendor/bundle || bundle install --deployment --jobs=4 --retry=3
      - save-cache: *save-bundler-cache
      - attach_workspace:
          at: ~/code
      - run: mv dist-www/ dist
      - run:
          name: Setup Environment
          command: echo 'export ENVIRONMENT=$(if [ "$CIRCLE_BRANCH" == "live" ]; then echo production; else echo staging; fi)' >> $BASH_ENV
      - run: bundle exec cap $ENVIRONMENT deploy:upload
      - run:
          name: Upload Source Map to Rollbar
          command: |
            curl https://api.rollbar.com/api/1/sourcemap/download -F access_token="${ROLLBAR_ACCESS_TOKEN}" -F version="${APP_VERSION}" -F minified_url=https://app-staging.goodcity.hk/assets/goodcity.js

workflows:
    version: 2
    build-test-and-deploy:
      jobs:
        - checkout_code
        - package_dependencies:
            requires:
              - checkout_code
        - tests:
            requires:
              - package_dependencies
        - upload-coverage:
            requires:
              - tests
            filters:
              branches:
                only: /^(master|live|push-plugin-upgrade)$/
        - www_build:
            requires:
              - tests
            filters:
              branches:
                only: /^(master|live|push-plugin-upgrade)$/
        - www_deploy:
            requires:
              - www_build
            filters:
              branches:
                only: /^(master|live|push-plugin-upgrade)$/
        - ember_cordova_build:
            requires:
              - tests
            filters:
              branches:
                only: /^(master|live|push-plugin-upgrade)$/
        - android_build_and_deploy:
            requires:
              - ember_cordova_build
            filters:
              branches:
                only: /^(master|live|push-plugin-upgrade)$/
        - ios_build_and_deploy:
            requires:
              - tests
            filters:
              branches:
                only: /^(master|live|push-plugin-upgrade)$/

